# Generated by Django 5.0 on 2023-12-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool_picker', '0002_criteria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Criteria',
        ),
        migrations.AddField(
            model_name='tool',
            name='biometrics',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tool',
            name='case_management',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tool',
            name='category',
            field=models.CharField(default='Uncategorized', max_length=100),
        ),
        migrations.AddField(
            model_name='tool',
            name='connectivity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tool',
            name='customized_workflows',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tool',
            name='data_cleaning',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tool',
            name='data_management_policies',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tool',
            name='data_security',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tool',
            name='data_viz',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tool',
            name='fsp_integration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tool',
            name='interoperability',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tool',
            name='localization',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tool',
            name='maintenance_complexity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tool',
            name='performance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tool',
            name='setup_complexity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tool',
            name='setup_speed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tool',
            name='sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tool',
            name='training_and_support',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tool',
            name='transition',
            field=models.IntegerField(default=0),
        ),
    ]
