# Generated by Django 5.0 on 2023-12-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool_picker', '0004_alter_tool_connectivity_alter_tool_data_cleaning_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='biometrics_desc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='case_management_desc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='connectivity_desc',
            field=models.TextField(default='No description provided.'),
        ),
        migrations.AddField(
            model_name='tool',
            name='customized_workflows_desc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='data_cleaning_desc',
            field=models.TextField(default='No description provided.'),
        ),
        migrations.AddField(
            model_name='tool',
            name='data_management_policies_desc',
            field=models.TextField(default='No description provided.'),
        ),
        migrations.AddField(
            model_name='tool',
            name='data_security_desc',
            field=models.TextField(default='No description provided.'),
        ),
        migrations.AddField(
            model_name='tool',
            name='data_viz_desc',
            field=models.TextField(default='No description provided.'),
        ),
        migrations.AddField(
            model_name='tool',
            name='fsp_integration_desc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='interoperability_desc',
            field=models.TextField(default='No description provided.'),
        ),
        migrations.AddField(
            model_name='tool',
            name='localization_desc',
            field=models.TextField(default='No description provided.'),
        ),
        migrations.AddField(
            model_name='tool',
            name='maintenance_complexity_desc',
            field=models.TextField(default='No description provided.'),
        ),
        migrations.AddField(
            model_name='tool',
            name='performance_desc',
            field=models.TextField(default='No description provided.'),
        ),
        migrations.AddField(
            model_name='tool',
            name='setup_complexity_desc',
            field=models.TextField(default='No description provided.'),
        ),
        migrations.AddField(
            model_name='tool',
            name='setup_speed_desc',
            field=models.TextField(default='No description provided.'),
        ),
        migrations.AddField(
            model_name='tool',
            name='sms_desc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='training_and_support_desc',
            field=models.TextField(default='No description provided.'),
        ),
        migrations.AddField(
            model_name='tool',
            name='transition_desc',
            field=models.TextField(default='No description provided.'),
        ),
    ]
