# Generated by Django 5.0 on 2023-12-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool_picker', '0005_tool_biometrics_desc_tool_case_management_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolPicker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intended_use_type', models.CharField(choices=[('emergency-response', 'Emergency Response'), ('non-emergency', 'Project')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ToolPickerResponses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='testimonial',
            name='related_emergency_name',
            field=models.CharField(default='No emergency specified.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='use_type',
            field=models.CharField(choices=[('emergency-response', 'Emergency Response'), ('non-emergency', 'Project')], default='Emergency Response', max_length=50),
        ),
    ]
