# Generated by Django 5.0 on 2023-12-18 16:16

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool_picker', '0006_toolpicker_toolpickerresponses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolAttributeDefinitions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.TextField(default='Not specified.')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='tool',
            name='cost',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Cost cannot be less than 0'), django.core.validators.MaxValueValidator(4, message='Cost cannot be greater than 4')]),
        ),
        migrations.AddField(
            model_name='tool',
            name='cost_desc',
            field=models.TextField(default='No description provided.'),
        ),
        migrations.AddField(
            model_name='toolpicker',
            name='available_budget',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Available budget cannot be less than 0'), django.core.validators.MaxValueValidator(4, message='Available budget cannot be greater than 4')]),
        ),
    ]
