# Generated by Django 5.0 on 2023-12-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool_picker', '0007_toolattributedefinitions_tool_cost_tool_cost_desc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toolattributedefinitions',
            old_name='cost',
            new_name='cost1',
        ),
        migrations.AddField(
            model_name='toolattributedefinitions',
            name='cost2',
            field=models.TextField(default='Not specified.'),
        ),
        migrations.AddField(
            model_name='toolattributedefinitions',
            name='cost3',
            field=models.TextField(default='Not specified.'),
        ),
        migrations.AddField(
            model_name='toolattributedefinitions',
            name='cost4',
            field=models.TextField(default='Not specified.'),
        ),
        migrations.AddField(
            model_name='toolattributedefinitions',
            name='cost_def',
            field=models.TextField(default='Not specified.'),
        ),
    ]
