# Generated by Django 5.0 on 2023-12-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool_picker', '0011_toolpickerresponses_available_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolpickerresponses',
            name='unique_id',
            field=models.CharField(default='Not entered.', max_length=100, null=True),
        ),
    ]
