# Generated by Django 5.0 on 2023-12-18 21:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool_picker', '0012_toolpickerresponses_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolattributedefinition',
            name='setup_time1',
            field=models.TextField(default='Not specified.', null=True),
        ),
        migrations.AddField(
            model_name='toolattributedefinition',
            name='setup_time2',
            field=models.TextField(default='Not specified.', null=True),
        ),
        migrations.AddField(
            model_name='toolattributedefinition',
            name='setup_time3',
            field=models.TextField(default='Not specified.', null=True),
        ),
        migrations.AddField(
            model_name='toolattributedefinition',
            name='setup_time4',
            field=models.TextField(default='Not specified.', null=True),
        ),
        migrations.AddField(
            model_name='toolattributedefinition',
            name='setup_time_def',
            field=models.TextField(default='Not specified.', null=True),
        ),
        migrations.AddField(
            model_name='toolpickerresponses',
            name='setup_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='toolpicker',
            name='available_budget',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Available budget cannot be less than 1'), django.core.validators.MaxValueValidator(4, message='Available budget cannot be greater than 4')]),
        ),
    ]
