# Generated by Django 5.0 on 2023-12-19 13:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool_picker', '0013_toolattributedefinition_setup_time1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolattributedefinition',
            name='closeout1',
            field=models.TextField(default='Not specified.', null=True),
        ),
        migrations.AddField(
            model_name='toolattributedefinition',
            name='closeout2',
            field=models.TextField(default='Not specified.', null=True),
        ),
        migrations.AddField(
            model_name='toolattributedefinition',
            name='closeout3',
            field=models.TextField(default='Not specified.', null=True),
        ),
        migrations.AddField(
            model_name='toolattributedefinition',
            name='closeout4',
            field=models.TextField(default='Not specified.', null=True),
        ),
        migrations.AddField(
            model_name='toolattributedefinition',
            name='closeout_def',
            field=models.TextField(default='Not specified.', null=True),
        ),
        migrations.AddField(
            model_name='toolattributedefinition',
            name='connectivity1',
            field=models.TextField(default='Not specified.', null=True),
        ),
        migrations.AddField(
            model_name='toolattributedefinition',
            name='connectivity2',
            field=models.TextField(default='Not specified.', null=True),
        ),
        migrations.AddField(
            model_name='toolattributedefinition',
            name='connectivity3',
            field=models.TextField(default='Not specified.', null=True),
        ),
        migrations.AddField(
            model_name='toolattributedefinition',
            name='connectivity4',
            field=models.TextField(default='Not specified.', null=True),
        ),
        migrations.AddField(
            model_name='toolattributedefinition',
            name='connectivity_def',
            field=models.TextField(default='Not specified.', null=True),
        ),
        migrations.AddField(
            model_name='toolattributedefinition',
            name='corresponding_tech1',
            field=models.TextField(default='Not specified.', null=True),
        ),
        migrations.AddField(
            model_name='toolattributedefinition',
            name='corresponding_tech2',
            field=models.TextField(default='Not specified.', null=True),
        ),
        migrations.AddField(
            model_name='toolattributedefinition',
            name='corresponding_tech3',
            field=models.TextField(default='Not specified.', null=True),
        ),
        migrations.AddField(
            model_name='toolattributedefinition',
            name='corresponding_tech4',
            field=models.TextField(default='Not specified.', null=True),
        ),
        migrations.AddField(
            model_name='toolattributedefinition',
            name='corresponding_tech_def',
            field=models.TextField(default='Not specified.', null=True),
        ),
        migrations.AddField(
            model_name='toolattributedefinition',
            name='data_cleaning1',
            field=models.TextField(default='Not specified.', null=True),
        ),
        migrations.AddField(
            model_name='toolattributedefinition',
            name='data_cleaning2',
            field=models.TextField(default='Not specified.', null=True),
        ),
        migrations.AddField(
            model_name='toolattributedefinition',
            name='data_cleaning3',
            field=models.TextField(default='Not specified.', null=True),
        ),
        migrations.AddField(
            model_name='toolattributedefinition',
            name='data_cleaning4',
            field=models.TextField(default='Not specified.', null=True),
        ),
        migrations.AddField(
            model_name='toolattributedefinition',
            name='data_cleaning_def',
            field=models.TextField(default='Not specified.', null=True),
        ),
        migrations.AddField(
            model_name='toolattributedefinition',
            name='data_privacy1',
            field=models.TextField(default='Not specified.', null=True),
        ),
        migrations.AddField(
            model_name='toolattributedefinition',
            name='data_privacy2',
            field=models.TextField(default='Not specified.', null=True),
        ),
        migrations.AddField(
            model_name='toolattributedefinition',
            name='data_privacy3',
            field=models.TextField(default='Not specified.', null=True),
        ),
        migrations.AddField(
            model_name='toolattributedefinition',
            name='data_privacy4',
            field=models.TextField(default='Not specified.', null=True),
        ),
        migrations.AddField(
            model_name='toolattributedefinition',
            name='data_privacy_def',
            field=models.TextField(default='Not specified.', null=True),
        ),
        migrations.AddField(
            model_name='toolattributedefinition',
            name='data_protection1',
            field=models.TextField(default='Not specified.', null=True),
        ),
        migrations.AddField(
            model_name='toolattributedefinition',
            name='data_protection2',
            field=models.TextField(default='Not specified.', null=True),
        ),
        migrations.AddField(
            model_name='toolattributedefinition',
            name='data_protection3',
            field=models.TextField(default='Not specified.', null=True),
        ),
        migrations.AddField(
            model_name='toolattributedefinition',
            name='data_protection4',
            field=models.TextField(default='Not specified.', null=True),
        ),
        migrations.AddField(
            model_name='toolattributedefinition',
            name='data_protection_def',
            field=models.TextField(default='Not specified.', null=True),
        ),
        migrations.AddField(
            model_name='toolattributedefinition',
            name='data_viz1',
            field=models.TextField(default='Not specified.', null=True),
        ),
        migrations.AddField(
            model_name='toolattributedefinition',
            name='data_viz2',
            field=models.TextField(default='Not specified.', null=True),
        ),
        migrations.AddField(
            model_name='toolattributedefinition',
            name='data_viz3',
            field=models.TextField(default='Not specified.', null=True),
        ),
        migrations.AddField(
            model_name='toolattributedefinition',
            name='data_viz4',
            field=models.TextField(default='Not specified.', null=True),
        ),
        migrations.AddField(
            model_name='toolattributedefinition',
            name='data_viz_def',
            field=models.TextField(default='Not specified.', null=True),
        ),
        migrations.AddField(
            model_name='toolattributedefinition',
            name='interoperability1',
            field=models.TextField(default='Not specified.', null=True),
        ),
        migrations.AddField(
            model_name='toolattributedefinition',
            name='interoperability2',
            field=models.TextField(default='Not specified.', null=True),
        ),
        migrations.AddField(
            model_name='toolattributedefinition',
            name='interoperability3',
            field=models.TextField(default='Not specified.', null=True),
        ),
        migrations.AddField(
            model_name='toolattributedefinition',
            name='interoperability4',
            field=models.TextField(default='Not specified.', null=True),
        ),
        migrations.AddField(
            model_name='toolattributedefinition',
            name='interoperability_def',
            field=models.TextField(default='Not specified.', null=True),
        ),
        migrations.AddField(
            model_name='toolattributedefinition',
            name='localization1',
            field=models.TextField(default='Not specified.', null=True),
        ),
        migrations.AddField(
            model_name='toolattributedefinition',
            name='localization2',
            field=models.TextField(default='Not specified.', null=True),
        ),
        migrations.AddField(
            model_name='toolattributedefinition',
            name='localization3',
            field=models.TextField(default='Not specified.', null=True),
        ),
        migrations.AddField(
            model_name='toolattributedefinition',
            name='localization4',
            field=models.TextField(default='Not specified.', null=True),
        ),
        migrations.AddField(
            model_name='toolattributedefinition',
            name='localization_def',
            field=models.TextField(default='Not specified.', null=True),
        ),
        migrations.AddField(
            model_name='toolattributedefinition',
            name='maintenance1',
            field=models.TextField(default='Not specified.', null=True),
        ),
        migrations.AddField(
            model_name='toolattributedefinition',
            name='maintenance2',
            field=models.TextField(default='Not specified.', null=True),
        ),
        migrations.AddField(
            model_name='toolattributedefinition',
            name='maintenance3',
            field=models.TextField(default='Not specified.', null=True),
        ),
        migrations.AddField(
            model_name='toolattributedefinition',
            name='maintenance4',
            field=models.TextField(default='Not specified.', null=True),
        ),
        migrations.AddField(
            model_name='toolattributedefinition',
            name='maintenance_def',
            field=models.TextField(default='Not specified.', null=True),
        ),
        migrations.AddField(
            model_name='toolattributedefinition',
            name='performance1',
            field=models.TextField(default='Not specified.', null=True),
        ),
        migrations.AddField(
            model_name='toolattributedefinition',
            name='performance2',
            field=models.TextField(default='Not specified.', null=True),
        ),
        migrations.AddField(
            model_name='toolattributedefinition',
            name='performance3',
            field=models.TextField(default='Not specified.', null=True),
        ),
        migrations.AddField(
            model_name='toolattributedefinition',
            name='performance4',
            field=models.TextField(default='Not specified.', null=True),
        ),
        migrations.AddField(
            model_name='toolattributedefinition',
            name='performance_def',
            field=models.TextField(default='Not specified.', null=True),
        ),
        migrations.AddField(
            model_name='toolattributedefinition',
            name='setup_complexity1',
            field=models.TextField(default='Not specified.', null=True),
        ),
        migrations.AddField(
            model_name='toolattributedefinition',
            name='setup_complexity2',
            field=models.TextField(default='Not specified.', null=True),
        ),
        migrations.AddField(
            model_name='toolattributedefinition',
            name='setup_complexity3',
            field=models.TextField(default='Not specified.', null=True),
        ),
        migrations.AddField(
            model_name='toolattributedefinition',
            name='setup_complexity4',
            field=models.TextField(default='Not specified.', null=True),
        ),
        migrations.AddField(
            model_name='toolattributedefinition',
            name='setup_complexity_def',
            field=models.TextField(default='Not specified.', null=True),
        ),
        migrations.AddField(
            model_name='toolattributedefinition',
            name='support1',
            field=models.TextField(default='Not specified.', null=True),
        ),
        migrations.AddField(
            model_name='toolattributedefinition',
            name='support2',
            field=models.TextField(default='Not specified.', null=True),
        ),
        migrations.AddField(
            model_name='toolattributedefinition',
            name='support3',
            field=models.TextField(default='Not specified.', null=True),
        ),
        migrations.AddField(
            model_name='toolattributedefinition',
            name='support4',
            field=models.TextField(default='Not specified.', null=True),
        ),
        migrations.AddField(
            model_name='toolattributedefinition',
            name='support_def',
            field=models.TextField(default='Not specified.', null=True),
        ),
        migrations.AddField(
            model_name='toolpicker',
            name='setup_time',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Setup time cannot be less than 1'), django.core.validators.MaxValueValidator(4, message='Setup time cannot be greater than 4')]),
        ),
    ]
