# Generated by Django 5.0 on 2023-12-19 14:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool_picker', '0014_toolattributedefinition_closeout1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolpicker',
            name='setup_complexity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Setup complexity cannot be less than 1'), django.core.validators.MaxValueValidator(4, message='Setup complexity cannot be greater than 4')]),
        ),
        migrations.AddField(
            model_name='toolpickerresponses',
            name='setup_complexity',
            field=models.IntegerField(default=0),
        ),
    ]
