# Generated by Django 5.0 on 2023-12-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool_picker', '0016_toolpicker_maintenance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolpickerresponses',
            name='closeout',
            field=models.IntegerField(default=0),
        ),
    ]
