# Generated by Django 5.0 on 2023-12-19 18:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool_picker', '0017_toolpickerresponses_closeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolpicker',
            name='closeout',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Closeout cannot be less than 1'), django.core.validators.MaxValueValidator(4, message='Closeout cannot be greater than 4')]),
        ),
    ]
