# Generated by Django 5.0 on 2023-12-19 19:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool_picker', '0019_toolpicker_support_toolpickerresponses_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolpicker',
            name='performance',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Performance and scalability cannot be less than 1'), django.core.validators.MaxValueValidator(4, message='Performance and scalability cannot be greater than 4')]),
        ),
        migrations.AddField(
            model_name='toolpickerresponses',
            name='performance',
            field=models.IntegerField(default=0),
        ),
    ]
