# Generated by Django 5.0 on 2023-12-19 19:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool_picker', '0021_toolpicker_connectivity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolpicker',
            name='data_cleaning',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Data cleaning cannot be less than 1'), django.core.validators.MaxValueValidator(4, message='Data cleaning cannot be greater than 4')]),
        ),
        migrations.AddField(
            model_name='toolpickerresponses',
            name='data_cleaning',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='toolpicker',
            name='connectivity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Connectivity cannot be less than 1'), django.core.validators.MaxValueValidator(4, message='Connectivity cannot be greater than 4')]),
        ),
    ]
