# Generated by Django 5.0 on 2023-12-19 19:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool_picker', '0025_toolpicker_localization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolpicker',
            name='data_privacy',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Data privacy cannot be less than 1'), django.core.validators.MaxValueValidator(4, message='Data privacy cannot be greater than 4')]),
        ),
        migrations.AddField(
            model_name='toolpicker',
            name='data_protection',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Data protection cannot be less than 1'), django.core.validators.MaxValueValidator(4, message='Data protection cannot be greater than 4')]),
        ),
        migrations.AddField(
            model_name='toolpickerresponses',
            name='data_privacy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='toolpickerresponses',
            name='data_protection',
            field=models.IntegerField(default=0),
        ),
    ]
