# Generated by Django 5.0 on 2024-01-30 20:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool_picker', '0026_toolpicker_data_privacy_toolpicker_data_protection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='data_privacy',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Data privacy cannot be less than 0'), django.core.validators.MaxValueValidator(4, message='Data privacy cannot be greater than 4')]),
        ),
        migrations.AddField(
            model_name='tool',
            name='data_privacy_desc',
            field=models.TextField(default='No description provided.'),
        ),
    ]
