# Generated by Django 5.0 on 2024-01-30 20:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool_picker', '0027_tool_data_privacy_tool_data_privacy_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tool',
            old_name='data_security_desc',
            new_name='data_protection_desc',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='data_security',
        ),
        migrations.AddField(
            model_name='tool',
            name='data_protection',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Data protection cannot be less than 0'), django.core.validators.MaxValueValidator(4, message='Data protection cannot be greater than 4')]),
        ),
    ]
