# Generated by Django 5.0 on 2024-02-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool_picker', '0028_rename_data_security_desc_tool_data_protection_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='tool',
            name='tool_features',
            field=models.ManyToManyField(related_name='tool', to='tool_picker.toolfeature'),
        ),
    ]
