# Generated by Django 5.0 on 2024-02-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool_picker', '0029_toolfeature_tool_tool_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolfeature',
            name='feature_category',
            field=models.CharField(default='None', max_length=300),
        ),
    ]
