# Generated by Django 5.0 on 2024-02-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool_picker', '0030_toolfeature_feature_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='tagline',
            field=models.TextField(default='No tagline provided', max_length=300),
        ),
    ]
