# Generated by Django 5.0 on 2024-02-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool_picker', '0031_tool_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='tool_image_url',
            field=models.TextField(default='none'),
        ),
    ]
