# Generated by Django 5.0 on 2024-02-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool_picker', '0032_tool_tool_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolResources',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='No tool resource name specified.', max_length=100, null=True)),
                ('category', models.CharField(default='No tool category specified.', max_length=200, null=True)),
                ('url', models.URLField(max_length=400)),
            ],
        ),
    ]
