# Generated by Django 5.0 on 2024-02-15 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool_picker', '0033_toolresources'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ToolResources',
            new_name='ToolResource',
        ),
    ]
