# Generated by Django 5.0 on 2024-02-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool_picker', '0034_rename_toolresources_toolresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='tool_resources',
            field=models.ManyToManyField(related_name='tool', to='tool_picker.toolresource'),
        ),
    ]
