# Generated by Django 5.0 on 2024-02-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool_picker', '0035_tool_tool_resources'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('language', models.CharField(default='No language name specified.', max_length=100, null=True)),
                ('ifrc_primary', models.BooleanField(default=False)),
            ],
        ),
    ]
