# Generated by Django 5.0 on 2024-02-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool_picker', '0036_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='languages',
            field=models.ManyToManyField(related_name='tool', to='tool_picker.language'),
        ),
    ]
