# Generated by Django 5.0 on 2024-02-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool_picker', '0037_tool_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolresource',
            name='category',
            field=models.CharField(choices=[('first_party_documentation', 'First Party Documentation'), ('support_forum', 'Support Forum'), ('tutorial', 'Tutorial'), ('documented_use_case', 'Documented Use Case')], default='No tool category specified.', max_length=200, null=True),
        ),
    ]
