# Generated by Django 5.0 on 2024-02-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool_picker', '0038_alter_toolresource_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolfeature',
            name='feature_category',
            field=models.CharField(choices=[('financial', 'Financial'), ('data_collection', 'Data Collection'), ('data_security', 'Data Security'), ('data_management', 'Data Management'), ('reporting_and_visualization', 'Reporting and Visualization')], default='None', max_length=300),
        ),
    ]
