# Generated by Django 5.0 on 2024-02-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool_picker', '0039_alter_toolfeature_feature_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolresource',
            name='category',
            field=models.CharField(choices=[('first_party_documentation', 'First Party Documentation'), ('support_forum', 'Support Forum'), ('tutorial', 'Tutorial'), ('documented_use_case', 'Documented Use Case')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='toolresource',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
