# Generated by Django 5.0 on 2024-02-16 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool_picker', '0040_alter_toolresource_category_alter_toolresource_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='biometrics',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='biometrics_desc',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='case_management',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='case_management_desc',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='customized_workflows',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='customized_workflows_desc',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='fsp_integration',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='fsp_integration_desc',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='sms',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='sms_desc',
        ),
    ]
