# Generated by Django 5.0 on 2024-02-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool_picker', '0041_remove_tool_biometrics_remove_tool_biometrics_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='tool_image_url',
            field=models.TextField(default='rc-select.s3.us-east-1.amazonaws.com/default_tool_icon.png'),
        ),
    ]
