# Generated by Django 5.0 on 2024-03-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool_picker', '0042_alter_tool_tool_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolfeature',
            name='feature_category',
            field=models.CharField(choices=[('configuration', 'Configuration'), ('beneficiary_registration', 'Beneficiary Registration'), ('distribution_planning_and_scheduling', 'Distribution Planning and Scheduling'), ('distribution_tracking', 'Distribution Tracking'), ('feedback_and_surveys', 'Feedback and Surveys'), ('data_management', 'Data Management'), ('reporting_and_analytics', 'Reporting and Analytics')], default='None', max_length=300),
        ),
    ]
