# Generated by Django 5.0 on 2024-03-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool_picker', '0043_alter_toolfeature_feature_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolfeature',
            name='cash_rtm_code',
            field=models.TextField(null=True),
        ),
    ]
