# Generated by Django 5.0 on 2024-03-04 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool_picker', '0044_toolfeature_cash_rtm_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolfeature',
            name='cash_rtm_code',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
