# Generated by Django 5.0 on 2024-03-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool_picker', '0046_rename_cash_rtm_code_toolfeature_cash_rtm_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolfeature',
            name='feature_category',
            field=models.CharField(choices=[('configuration', 'Configuration'), ('beneficiary_registration', 'Beneficiary Registration'), ('distribution_management', 'Distribution Management'), ('feedback_and_surveys', 'Feedback and Surveys'), ('data_management', 'Data Management'), ('reporting_and_analytics', 'Reporting and Analytics')], default='None', max_length=300),
        ),
    ]
